In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(df, iris.target, test_size= 0.3)

In [34]:
from sklearn.svm import SVC

In [35]:
model= SVC()
model.fit(X_train, y_train)
model.score(X_test,y_test)

0.9777777777777777

## Lets check the score on different parameters of svc using cross validation

In [36]:
from sklearn.model_selection import cross_val_score

In [39]:
cross_val_score(SVC(kernel='rbf', gamma='auto', C=1),df, iris.target,cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [42]:
cross_val_score(SVC(kernel='rbf', gamma='auto', C=11),df, iris.target,cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [43]:
cross_val_score(SVC(kernel='linear', gamma='auto', C=21),df, iris.target,cv = 5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

## Theres another simplest way to do it.

In [45]:
from sklearn.model_selection import GridSearchCV

In [49]:
clf = GridSearchCV(SVC(gamma='auto'), {
    'C' : [10, 20, 30],
    'kernel' : ['rbf', 'linear']
}, cv = 5 , return_train_score = False )

clf.fit(df, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.01532941, 0.00434079, 0.00238256, 0.00378819, 0.00247669,
        0.00332589]),
 'std_fit_time': array([0.0207899 , 0.00401328, 0.00353903, 0.00399485, 0.00286196,
        0.00347072]),
 'mean_score_time': array([0.00382137, 0.00217619, 0.00396643, 0.00195565, 0.00111947,
        0.00277801]),
 'std_score_time': array([0.00317364, 0.00176843, 0.00266494, 0.00292834, 0.00146392,
        0.0020759 ]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score'

In [50]:
d = pd.DataFrame(clf.cv_results_)
d.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.015329      0.020790         0.003821        0.003174       10   
1       0.004341      0.004013         0.002176        0.001768       10   
2       0.002383      0.003539         0.003966        0.002665       20   
3       0.003788      0.003995         0.001956        0.002928       20   
4       0.002477      0.002862         0.001119        0.001464       30   

  param_kernel                         params  split0_test_score  \
0          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
1       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
2          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.900000           0.966667                1.0   
2                1.0           0.900000           0.966667                1.0   
3                1.0           0.900000           0.933333                1.0   
4                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.973333        0.038873                2  
2         0.966667        0.036515                3  
3         0.966667        0.042164                4  
4         0.960000        0.038873                5

In [51]:
clf.best_score_

0.9800000000000001

In [52]:
clf.best_params_

{'C': 10, 'kernel': 'rbf'}

## Imagine you have millions of data then this method will take much more time therefore we have another method for this

In [53]:
from sklearn.model_selection import RandomizedSearchCV

In [56]:
rs = RandomizedSearchCV(SVC(gamma= 'auto'), {
    'C' : [10, 20, 30],
    'kernel' : ['rbf', 'linear']
}, cv = 5 , return_train_score = False, n_iter = 2)

rs.fit(df, iris.target)
rs.cv_results_

{'mean_fit_time': array([0.00557141, 0.00653586]),
 'std_fit_time': array([0.00133976, 0.0042077 ]),
 'mean_score_time': array([0.00628428, 0.00439038]),
 'std_score_time': array([0.0061501, 0.0071183]),
 'param_kernel': masked_array(data=['rbf', 'rbf'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[20, 10],
              mask=[False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 20}, {'kernel': 'rbf', 'C': 10}],
 'split0_test_score': array([0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.96666667, 0.98      ]),
 'std_test_score': array([0.03651484, 0.01632993]),
 'rank_test_score': array([2, 1])}

In [60]:
drs = pd.DataFrame(rs.cv_results_)
drs.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.005571      0.001340         0.006284        0.006150          rbf   
1       0.006536      0.004208         0.004390        0.007118          rbf   

   param_C                      params  split0_test_score  split1_test_score  \
0       20  {'kernel': 'rbf', 'C': 20}           0.966667                1.0   
1       10  {'kernel': 'rbf', 'C': 10}           0.966667                1.0   

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           0.900000           0.966667                1.0         0.966667   
1           0.966667           0.966667                1.0         0.980000   

   std_test_score  rank_test_score  
0        0.036515                2  
1        0.016330                1

In [67]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,9]
        }
    }
}

In [68]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}