In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_digits

In [3]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size= 0.3)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9537037037037037

In [15]:
from sklearn.svm import SVC

In [16]:
svc = SVC()
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

0.9907407407407407

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975925925925926

In [19]:
from sklearn.model_selection import KFold

In [20]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
def getScore(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

## Appling Stratified KFlod

In [24]:
from sklearn.model_selection import StratifiedKFold

In [30]:
sk = StratifiedKFold(n_splits=5)

lrScore = []
svmScore = []
rfScore = []

for train_index,test_index in sk.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    lrScore.append(getScore(LogisticRegression(), X_train, X_test, y_train, y_test))
    svmScore.append(getScore(SVC(), X_train, X_test, y_train, y_test))
    rfScore.append(getScore(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [28]:
lrScore

[0.9222222222222223,
 0.8694444444444445,
 0.9415041782729805,
 0.9387186629526463,
 0.8969359331476323]

In [31]:
svmScore

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [33]:
rfScore

[0.9277777777777778,
 0.9333333333333333,
 0.9610027855153204,
 0.9610027855153204,
 0.9220055710306406]

## Cross Validation

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [36]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [37]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93611111, 0.91666667, 0.96657382, 0.94986072, 0.9275766 ])